authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import LoginView, RegisterView, LogoutView, EditView


app_name = AuthappConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("edit/", EditView.as_view(), name="edit"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
    # path(
    #     "mainapp/news/<term>/",
    #     RedirectView.as_view(url="https://google.com/?q=%(term)s"),
    # ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

mainapp/urls.py
from django.urls import path

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("news/", views.NewsView.as_view(), name="news"),
    path("courses/", views.CoursesView.as_view(), name="courses"),
    path("contacts/", views.ContactsView.as_view(), name="contacts"),
    path("doc_site/", views.DocSiteView.as_view(), name="doc_site"),
    path("login/", views.LoginView.as_view(), name="login"),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from mainapp.models import NULLABLE


class User(AbstractUser):
    email = models.EmailField(blank=True, verbose_name=_("Email"), unique=True)
    age = models.PositiveSmallIntegerField(verbose_name="Возраст", **NULLABLE)
    avatar = models.ImageField(upload_to="users", **NULLABLE)

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

mainapp/models.py
from django.db import models

# Create your models here.

NULLABLE = {"blank": True, "null": True}


class BaseModel(models.Model):

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Created", editable=False
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Edited", editable=False
    )
    deleted = models.BooleanField(default=False)

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        abstract = True
        ordering = ("-created_at",)


class News(BaseModel):

    title = models.CharField(max_length=256, verbose_name="Title")
    preamble = models.CharField(max_length=1024, verbose_name="Preamble")
    body = models.TextField(verbose_name="Body", **NULLABLE)
    body_as_markdown = models.BooleanField(
        default=False, verbose_name="As markdown"
    )

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    class Meta:
        verbose_name = "новость"
        verbose_name_plural = "новости"


class Course(BaseModel):

    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", **NULLABLE)
    description_as_markdown = models.BooleanField(
        verbose_name="As markdown", default=False
    )
    cost = models.DecimalField(
        max_digits=8, decimal_places=2, verbose_name="Cost", default=0
    )
    cover = models.CharField(
        max_length=25, default="no_image.svg", verbose_name="Cover"
    )

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    class Meta:
        verbose_name = "курс"
        verbose_name_plural = "курсы"


class Lesson(BaseModel):

    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", **NULLABLE)
    description_as_markdown = models.BooleanField(
        verbose_name="As markdown", default=False
    )

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        verbose_name = "урок"
        verbose_name_plural = "уроки"
        ordering = ("course", "num")


class CoursesTeacher(BaseModel):

    courses = models.ManyToManyField(Course)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(
            self.pk, self.name_second, self.name_first
        )

authapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class LoginView(TemplateView):
    template_name = "authapp/login.html"


class RegisterView(TemplateView):
    template_name = "authapp/register.html"


class LogoutView(TemplateView):
    pass


class EditView(TemplateView):
    pass

mainapp/views.py
# import os
from datetime import datetime

# import requests
from black import Any, Dict
from django.views.generic import TemplateView
from dotenv import load_dotenv

from mainapp.models import News

load_dotenv()


class IndexView(TemplateView):
    template_name = "mainapp/index.html"


class NewsView(TemplateView):
    template_name = "mainapp/news.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        context = super().get_context_data(**kwargs)

        # lesson3  3. На странице новостей организуйте цикл, где выводятся карточки новостей (5 одинаковых карточек).

        # context["range"] = range(1, 6)
        # context["new"] = {
        #     "title": "Новостной заголовок",
        #     "preview": ["Предварительное описание", "-й новости"],
        #     "date": datetime.now(),
        # }

        # lesson3  6. (*) Сформируйте JSON-файл и разместите в нём несколько сгенерированных новостей с заголовками,
        # Затем выведите их в цикле на странице новостей.

        # API_KEY = str(os.getenv("API_KEY"))

        # url = f"https://newsapi.org/v2/top-headlines?country=ru&category=technology&apiKey={API_KEY}"
        # news = requests.get(url).json()

        # new_title = []
        # description = []
        # img = []
        # publishedAt = []

        # for new in news["articles"]:
        #     new_title.append(new["title"])
        #     description.append(new["description"])
        #     img.append(new["urlToImage"])
        #     publishedAt.append(new["publishedAt"])

        # context["myNewscast"] = zip(new_title, description, img, publishedAt)

        # lesson 4
        context["newscast"] = News.objects.all()

        return context


class CoursesView(TemplateView):
    template_name = "mainapp/courses_list.html"


class ContactsView(TemplateView):
    template_name = "mainapp/contacts.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        context = super().get_context_data(**kwargs)

        map = [
            "https://yandex.ru/map-widget/v1/-/CCUAZHcrhA",
            "https://yandex.ru/map-widget/v1/-/CCUAZHX3xB",
            "https://yandex.ru/map-widget/v1/-/CCUAZHh9kD",
        ]
        city = [
            "Санкт‑Петербург",
            "Казань",
            "Москва",
        ]
        phone = [
            "+7-999-11-11111",
            "+7-999-22-22222",
            "+7-999-33-33333",
        ]
        email = [
            "geeklab@spb.ru",
            "geeklab@kz.ru",
            "geeklab@msk.ru",
        ]
        address = [
            "территория Петропавловская крепость, 3Ж",
            "территория Кремль, 11, Казань, Республика Татарстан, Россия",
            "Красная площадь, 7, Москва, Россия",
        ]
        context["contacts"] = zip(map, city, phone, email, address)

        return context


class DocSiteView(TemplateView):
    template_name = "mainapp/doc_site.html"


class LoginView(TemplateView):
    template_name = "mainapp/login.html"

authapp/templates/authapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- ChartJS -->
  <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

  <!-- FontAwesome -->
  <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

  <title>Welcome to GeekLab!</title>
</head>

<body>

{% include 'authapp/includes/inc_messages.html' %} 

  <div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
    <div class="text-center">
      <p>
        <a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
      </p>
      <h2>Вход пользователя</h2>
      {% block content %}
      {% endblock %}
    </div>
  </div>


  <!-- JavaScript section -->
  <!-- Bootstrap -->
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- ChartJs -->
  <script src="{% static 'js/Chart.min.js' %}"></script>

  <!-- FontAwesome -->
  <script src="{% static 'js/fontawesome.all.min.js' %}"></script>

</body>

</html>

authapp/templates/authapp/includes/inc_messages.html
<div class="position-absolute w-100" style="z-index: 1;">
    <div aria-live="polite" aria-atomic="true" class="m-2">
        <!-- Position it -->
        <div class="d-flex align-items-end flex-column">
            {% for message in messages %}
            <!-- Then put toasts within -->
            <div class="toast flex-fill w-100
    {% if message.level == 30 %}
    border-warning
    {% endif %}
" role="alert" aria-live="assertive" aria-atomic="true" style="right: 0;">
                <div class="toast-header">
                    <span class="mr-2"><i class="far fa-envelope"></i></span>
                    <strong class="mr-auto {% if message.level == 30 %}text-warning{% endif %}">
                        {{ message.tags|capfirst }} message</strong>
                    <small class="text-muted">just now</small>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    {{ message }}
                </div>
            </div>
            {% if message.level > 20 %}
            <!-- If message will dissipate you will find message in console -->
            <script>
                console.log("{{ message }}");
            </script>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html'  %}
{% block content %}
<form> 
  <p>
    <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя"
      required="" autofocus="">
  </p>
  <p>
    <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль" required="">
  </p>
  <p>
    <button type="submit" class="btn btn-primary btn-block">Войти</button>
  </p>
</form>
<p class="text-right">
  <a href=""><small>Забыли пароль?</small></a>
</p>
<h4>Вход через социальные сети</h4>
<p>
<div class="btn-group btn-block" role="group">
  <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
  <a class="btn btn-primary" href="#" role="button"><i class="fab fa-github"></i></a>
  <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
</div>
</p>
{% endblock %}

authapp/templates/authapp/logout.html
<div>
    <p></p>
</div>

authapp/templates/authapp/register.html
{% extends 'authapp/base.html'  %}
{% block content %}
<form> 
  register
</form>
<p class="text-right">
  <a href=""><small>Забыли пароль?</small></a>
</p>
<h4>Вход через социальные сети</h4>
<p>
<div class="btn-group btn-block" role="group">
  <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
  <a class="btn btn-primary" href="#" role="button"><i class="fab fa-github"></i></a>
  <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
</div>
</p>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to Braniac!</title>
</head>

<body>



    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'mainapp:index' %}">
                <img src="{% static 'img/logo.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            {% include "mainapp/includes/inc_main_menu.html" %}
        </div>
    </nav>


    <div class="container-md">

        {% block content %}

        {% endblock %}

    </div>


    <!-- Footer -->

    <div class="container-lg mt-auto">
        <hr>
        <div class="row justify-content-center">
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Braniac</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="index.html">Домашняя</a></li>
                    <li><a href="news.html">Новости</a></li>
                    <li><a href="login.html">Войти</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Полезное</strong>
                </p>
                <p>
                <ul class="list-unstyled">
                    <li><a href="#">Положения &amp; Условия</a></li>
                    <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                    <li><a href="#">Документация по API</a></li>
                    <li><a href="doc_site.html">Документация по сайту</a></li>
                </ul>
                </p>
            </div>
            <div class="col-sm-6 col-md-3 text-center">
                <p>
                    <strong>Мы в социальных сетях</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
                </div>
                </p>
                <p>
                    <strong>Наше приложение</strong>
                </p>
                <p>
                <div class="row justify-content-around">
                    <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                    <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
                </div>
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div>
                <p><small>&copy; GeekBrains 2021</small></p>
            </div>
        </div>
    </div>

    <!-- /Footer -->




    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>



</body>

</html>

mainapp/templates/mainapp/contacts.html
{% extends 'base.html' %}

{% block content %}

{% load mailto %}

<p>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Наши контакты</h1>
    <p class="lead">Обязательно свяжитесь с нами! Ваш комфорт - наша забота.</p>
  </div>
</div>
</p>
<p>
<div class="row justify-content-around mt-n2">

  {% for map, city, phone, email, address in contacts %}
  <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
    <div class="card h-100 shadow">
      <div class="card-body">
        <div style="position:relative;overflow:hidden;">

          <iframe src="{{ map }}" width="100%" height="300" frameborder="0" allowfullscreen="true"
            style="position:relative; border-radius: 4px;">
          </iframe>
        </div>
        <h5 class="card-title">{{ city }}</h5>
        <p class="card-text">
        <ul class="list-unstyled">
          <li>Телефон</li>
          <li><strong>{{ phone }}</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Email</li>
          <li><strong>{{ email|mail_to }}</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Адрес</li>
          <li><strong>{{ address }}</strong></li>
        </ul>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}

</div>
</p>


{% endblock content %}

<!-- <a href="https://yandex.ru/maps/org/petropavlovskaya_krepost/146720535721/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:0px;">
            Петропавловская крепость
          </a>
          <a href="https://yandex.ru/maps/2/saint-petersburg/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:14px;">
            Достопримечательность в Санкт‑Петербурге
          </a>
          <a href="https://yandex.ru/maps/2/saint-petersburg/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:28px;">
            Музей в Санкт‑Петербурге
          </a> -->

<!-- <a href="https://yandex.ru/maps/org/kazanskiy_kreml/95813866834/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:0px;">
            Казанский Кремль
          </a>
          <a href="https://yandex.ru/maps/43/kazan/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:14px;">
            Музей в Казани
          </a>
          <a href="https://yandex.ru/maps/43/kazan/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:28px;">
            Достопримечательность в Казани
          </a> -->

<!-- <a href="https://yandex.ru/maps/org/sobor_pokrova_presvyatoy_bogoroditsy_na_rvu/175159255687/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:0px;">
            Собор Покрова Пресвятой Богородицы на Рву
          </a>
          <a href="https://yandex.ru/maps/213/moscow/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
            style="color:#eee;font-size:12px;position:absolute;top:14px;">
            Музей в Москве
          </a> -->

mainapp/templates/mainapp/courses_list.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<div class="row justify-content-center mt-3">


    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
        <a href="#">
            <img src="{% static 'img/course001.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Web Python</h5>
            </div>
        </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
        <a href="#">
            <img src="{% static 'img/course002.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Web Golang</h5>
            </div>
        </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
        <a href="#">
            <img src="{% static 'img/course003.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Web JavaScript</h5>
            </div>
        </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
        <a href="#">
            <img src="{% static 'img/course004.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Web Java</h5>
            </div>
        </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
        <a href="#">
            <img src="{% static 'img/course005.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Web PHP</h5>
            </div>
        </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
        <a href="#">
            <img src="{% static 'img/course006.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">Python AI</h5>
            </div>
        </a>
    </div>



    <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
        <a href="#">
            <img src="{% static 'img/course007.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title text-center">DevOps</h5>
            </div>
        </a>
    </div>


</div>
<div class="row justify-content-center align-items-center mt-3 mb-n3">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>


{% endblock content %}

mainapp/templates/mainapp/doc_site.html
{% extends 'base.html' %}

{% block content %}


<div class="row justify-content-center align-items-center mt-3">
    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Документация по сайту
            </div>
            <div class="card-body">

                <h5 class="card-title">CSS-стили</h5>
                <p class="card-text">
                <ul>
                    <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/"
                            target="_blank">Bootstrap v4.6</a></li>
                    <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
                </ul>
                </p>

                <h5 class="card-title">Иконки</h5>
                <p class="card-text">
                    <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">
                        FontAwesome 5.15.3
                    </a>
                </p>

                <h5 class="card-title">Графики</h5>
                <p class="card-text">
                    <a href="https://www.chartjs.org/">ChartJS</a>
                </p>

                <h5 class="card-title">Графика</h5>
                <p class="card-text">
                <ul>
                    <li>
                        <a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">
                            Логотип by flamingtext.com
                        </a>
                    </li>
                    <li>
                        <a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">
                            Фотографии by pexels.com
                        </a>
                        . Все изображения распространяются под бесплатной лицензией. Для страницы обзоров
                        фотографии должны быть с соотношением сторон кратным 2.912 (например, 1920x659)
                    </li>
                    <li>
                        <a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">
                            Аватарки пользователей by getavataaars.com
                        </a>
                    </li>
                </ul>
                </p>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/includes/inc_main_menu.html
{% load static %}

<!-- {% with request.resolver_match.url_name as view_name %} -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:index' %}">
            <img src="{% static 'img/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if view_name == 'news' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
                </li>
                <li class="nav-item {% if view_name == 'courses' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:courses' %}">Курсы</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Профиль
                    </a>
                    <div class="dropdown-menu" aria-labelledby="ddProfile">
                        <a class="dropdown-item" href="#">Редактировать профиль</a>
                        <a class="dropdown-item" href="#">Мои курсы</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Модерация</a>
                        <a class="dropdown-item" href="#">Административный раздел</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Выход</a>
                    </div>
                </li>
                <li class="nav-item {% if view_name == 'contacts' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
                </li>
            </ul>
            <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
        </div>
    </div>
</nav>

<!-- {% endwith %} -->